# Generated by Django 3.0.8 on 2020-09-09 13:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente_obstetricia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['-cedula'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id_historia_parto', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('presenta', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('controles', models.IntegerField()),
                ('deseado', models.BooleanField(default=False)),
                ('planificado', models.BooleanField(default=False)),
                ('controlado', models.BooleanField(default=False)),
                ('itu', models.BooleanField(default=False)),
                ('laboratorio', models.TextField()),
                ('fecha', models.CharField(max_length=15)),
                ('medico_nombre', models.CharField(max_length=50)),
                ('medico_apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('rango', models.CharField(max_length=30)),
                ('rango2', models.CharField(blank=True, max_length=30, null=True)),
                ('rango3', models.CharField(blank=True, max_length=30, null=True)),
                ('ci_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstetricia.Paciente_obstetricia')),
            ],
            options={
                'ordering': ['-ci_paciente'],
            },
        ),
        migrations.CreateModel(
            name='Orden_medica_parto',
            fields=[
                ('id_orden_medica_parto', models.AutoField(primary_key=True, serialize=False)),
                ('orden_uno', models.CharField(max_length=50)),
                ('orden_dos', models.CharField(max_length=50)),
                ('orden_tres', models.CharField(max_length=50)),
                ('orden_cuatro', models.CharField(max_length=50)),
                ('orden_cinco', models.CharField(max_length=50)),
                ('orden_seis', models.CharField(max_length=50, null=True)),
                ('orden_siete', models.CharField(max_length=50, null=True)),
                ('orden_ocho', models.CharField(max_length=50, null=True)),
                ('orden_nueve', models.CharField(max_length=50, null=True)),
                ('orden_diez', models.CharField(max_length=50, null=True)),
                ('fecha', models.CharField(max_length=50)),
                ('medico_nombre', models.CharField(max_length=50)),
                ('medico_apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('rango', models.CharField(max_length=30)),
                ('rango2', models.CharField(blank=True, max_length=30, null=True)),
                ('rango3', models.CharField(blank=True, max_length=30, null=True)),
                ('ci_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstetricia.Paciente_obstetricia')),
            ],
            options={
                'ordering': ['-ci_paciente'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_historia_nota_parto', models.AutoField(primary_key=True, serialize=False)),
                ('nota_uno', models.CharField(max_length=100)),
                ('nota_dos', models.CharField(max_length=100)),
                ('nota_tres', models.CharField(max_length=100)),
                ('nota_cuatro', models.CharField(max_length=100)),
                ('nota_cinco', models.CharField(max_length=100)),
                ('nota_seis', models.CharField(max_length=100, null=True)),
                ('nota_siete', models.CharField(max_length=100, null=True)),
                ('nota_ocho', models.CharField(max_length=100, null=True)),
                ('nota_nueve', models.CharField(max_length=100, null=True)),
                ('nota_diez', models.CharField(max_length=100, null=True)),
                ('diagnostico2', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=50)),
                ('medico_nombre', models.CharField(max_length=50)),
                ('medico_apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('rango', models.CharField(max_length=30)),
                ('rango2', models.CharField(blank=True, max_length=30, null=True)),
                ('rango3', models.CharField(blank=True, max_length=30, null=True)),
                ('ci_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstetricia.Paciente_obstetricia')),
            ],
            options={
                'ordering': ['-ci_paciente'],
            },
        ),
        migrations.CreateModel(
            name='Examen_fisico',
            fields=[
                ('id_examen_fisico', models.AutoField(primary_key=True, serialize=False)),
                ('ta', models.CharField(max_length=10)),
                ('fc', models.CharField(max_length=10)),
                ('fr', models.CharField(max_length=10)),
                ('cardio_pul', models.CharField(max_length=200)),
                ('mamas', models.CharField(max_length=200)),
                ('abdomen', models.CharField(max_length=200)),
                ('feto', models.CharField(max_length=200)),
                ('normoconfigurados', models.CharField(max_length=200)),
                ('cuello_uterino', models.CharField(max_length=200)),
                ('extremidades', models.CharField(max_length=200)),
                ('neurologico', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=15)),
                ('medico_nombre', models.CharField(max_length=50)),
                ('medico_apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('rango', models.CharField(max_length=30)),
                ('rango2', models.CharField(blank=True, max_length=30, null=True)),
                ('rango3', models.CharField(blank=True, max_length=30, null=True)),
                ('ci_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstetricia.Paciente_obstetricia')),
            ],
            options={
                'ordering': ['-ci_paciente'],
            },
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id_antecedentes', models.AutoField(primary_key=True, serialize=False)),
                ('fur', models.CharField(max_length=11)),
                ('gestas', models.IntegerField()),
                ('partos', models.IntegerField()),
                ('cesareas', models.IntegerField()),
                ('legrados', models.IntegerField()),
                ('antemadre', models.CharField(max_length=100)),
                ('antepadre', models.CharField(max_length=100)),
                ('antehermanos', models.CharField(max_length=100)),
                ('antehijos', models.CharField(max_length=100)),
                ('patologias', models.CharField(max_length=100)),
                ('alergias', models.CharField(max_length=100)),
                ('transfusiones', models.CharField(max_length=100)),
                ('intervenciones', models.CharField(max_length=100)),
                ('menarquia', models.IntegerField()),
                ('sexarquia', models.IntegerField()),
                ('ciclomens', models.CharField(max_length=30)),
                ('parejas', models.IntegerField()),
                ('aco', models.BooleanField(default=False)),
                ('citologia', models.BooleanField(default=False)),
                ('its', models.BooleanField(default=False)),
                ('diu', models.BooleanField(default=False)),
                ('embarazo_ante', models.CharField(max_length=200)),
                ('ci_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstetricia.Paciente_obstetricia')),
            ],
            options={
                'ordering': ['-ci_paciente'],
            },
        ),
        migrations.CreateModel(
            name='Medico_obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('genero', models.CharField(max_length=10)),
                ('rango', models.CharField(max_length=30)),
                ('rango2', models.CharField(max_length=30)),
                ('rango3', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
