# Generated by Django 3.0.8 on 2020-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_fisico',
            name='fc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='fr',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examen_fisico',
            name='ta',
            field=models.CharField(max_length=20),
        ),
    ]
