# Generated by Django 3.0.8 on 2020-10-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico_obs',
            name='correo',
        ),
    ]
