# Generated by Django 3.0.8 on 2020-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0002_auto_20200909_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_medica_parto',
            name='orden_diez',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden_medica_parto',
            name='orden_nueve',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden_medica_parto',
            name='orden_ocho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden_medica_parto',
            name='orden_seis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden_medica_parto',
            name='orden_siete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
