# Generated by Django 3.0.8 on 2020-10-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0004_auto_20200930_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota_seis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden_medica_parto',
            name='orden_seis',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
